load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

system_cxx_toolchain(
    name = "cxx",
    cxx_flags = ["-Os", "-flto=thin"],
    link_flags = ["-Os", "-Wl,-O4", "-flto=thin"],
    linker = "clang",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    rustc_flags = ["-Copt-level=s", "-Cdebuginfo=1", "-Cstrip=symbols", "-Clto=thin", "-Cpanic=abort", "-Zdylib-lto"],
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)
